# Generated by Django 4.2.5 on 2023-10-15 14:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_booking_client_booking_date_booking_timeslot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='timeslot',
            field=models.SmallIntegerField(default=10, validators=[django.core.validators.MaxValueValidator(22), django.core.validators.MinValueValidator(9)]),
        ),
    ]
