# Generated by Django 4.2.5 on 2023-10-15 14:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_alter_booking_timeslot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='timeslot',
            field=models.SmallIntegerField(default=12, validators=[django.core.validators.MaxValueValidator(22), django.core.validators.MinValueValidator(8)]),
        ),
    ]
