# Generated by Django 4.2.5 on 2023-10-17 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_alter_booking_timeslot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='timeslot',
            new_name='hour',
        ),
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('date', 'hour')},
        ),
    ]
